baseURL = "https://world1tree.github.io/"
languageCode = "en-us"
title = "World1tree"
theme="archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
    mode="auto" # color-mode → light,dark or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "*Start where you are. Use what you have. Do what you can!* ~[*Arthur Ashe*](https://en.wikipedia.org/wiki/Arthur_Ashe)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/world1tree"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/world1tree/"

# Main menu Items

[[menu.main]]
name = "Archives"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2
